name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y make cmake g++ libaio-dev libgoogle-perftools-dev libunwind-dev clang-format libboost-dev libboost-program-options-dev libmkl-full-dev libcpprest-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build C++ code
        run: |
          mkdir -p build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -- -j

      - name: Run Python script
        run: |
          python RunAndEval.py --results ./results.csv --dataname ccnews-fp16 --R 64 --LB 100 --B 3 --M 4 --T 8 -LS 200 --K 30

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: results
          path: results.csv
