name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t diskann-ci .

      - name: Run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace diskann-ci \
            bash -c "cp /app/DiskANN/results.csv /workspace/results.csv || true"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.csv
